.github/workflows/nodejs.yml

This PR adds the deployment code to deploy the website to Firebase.
@hernaneg350 you still need to the following:
- Perform a `firebase login:ci`
- Grab the token you've received and put it into a secret with the name `FIREBASE_TOKEN`. Secrets are located in Settings -> Secrets.

Add github actions deployment

---

__types__/ImpactBanner_data.graphql.ts
__types__/ImpactItem_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/sections/ImpactBanner/ImpactBanner.scss
components/sections/ImpactBanner/ImpactBanner.tsx
components/sections/ImpactBanner/ImpactBanner.types.ts
components/sections/ImpactBanner/components/ImpactItem/ImpactItem.scss
components/sections/ImpactBanner/components/ImpactItem/ImpactItem.tsx
components/sections/ImpactBanner/components/ImpactItem/ImpactItem.types.ts
components/sections/index.ts
package-lock.json
pages/[...site].tsx
schema/schema.graphql

Add impact today section of the landing
- Add IconList customType
- Add "Impacto Hoy" content
- Add Impacto Hoy content to the Landing Home page.

Add impact today section

---

__types__/NewsBanner_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/sections/NewsBanner/NewsBanner.scss
components/sections/NewsBanner/NewsBanner.tsx
components/sections/NewsBanner/NewsBanner.types.ts
components/sections/index.ts
pages/[...site].tsx
schema/schema.graphql

Add home news section with links to the articles

Add news section to home

---

__types__/Founder_data.graphql.ts
__types__/HomeBanner_data.graphql.ts
__types__/IconTabs_data.graphql.ts
__types__/ImpactBanner_data.graphql.ts
__types__/ImpactItem_data.graphql.ts
__types__/NewsBanner_data.graphql.ts
__types__/Presentation_data.graphql.ts
__types__/SiteQuery.graphql.ts
__types__/Tabs_data.graphql.ts
components/sections/IconTabs/IconTabs.scss
components/sections/IconTabs/IconTabs.tsx
components/sections/IconTabs/IconTabs.types.ts
components/sections/ImpactBanner/ImpactBanner.scss
components/sections/ImpactBanner/ImpactBanner.tsx
components/sections/NewsBanner/NewsBanner.scss
components/sections/NewsBanner/NewsBanner.tsx
components/sections/Tabs/Tabs.tsx
components/sections/index.ts
pages/[...site].tsx
schema/schema.graphql

Add word axes section and its types

Add "Ejes de trabajo" section

---

__types__/Donations_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/sections/Donations/Donations.container.ts
components/sections/Donations/Donations.tsx
components/sections/Donations/Donations.types.ts
components/sections/Donations/index.ts
components/sections/index.ts
pages/[...site].tsx
schema/schema.graphql

This component adds the donation section.
There's no picture associated with it because we can't render it due to restrictions with the donar-online website.
The component renders an iframe with the URL of the iframe being configurable.

Adds donation component

---

__types__/Header_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/DocumentLink/DocumentLink.tsx
components/sections/Header/Header.tsx
components/sections/Header/HeaderDesktop/HeaderDeskop.tsx
components/sections/Header/HeaderDesktop/HeaderDesktop.scss
components/sections/Header/HeaderMobile/HeaderMobile.scss
components/sections/Header/HeaderMobile/HeaderMobile.tsx
schema/schema.graphql

Add links to document in the header component

add header links

---

components/sections/Footer/Footer.scss
components/sections/Footer/Footer.tsx
lib/prismicTypes.ts
schema/schema.graphql

Desktop style and pata-pila logo are missing.
iPhone X (375px):
iPhone 5 (320px, smallest screen)
Desktop:

Add footer content and style it for mobile

---

components/Responsive/Response.scss
components/sections/IconTabs/IconTabs.container.tsx
components/sections/IconTabs/IconTabsDesktop/IconTabsDesktop.scss
components/sections/IconTabs/IconTabsDesktop/IconTabsDesktop.tsx
components/sections/IconTabs/IconTabsDesktop/index.ts
components/sections/IconTabs/IconTabsMobile/IconTabsMobile.scss
components/sections/IconTabs/IconTabsMobile/IconTabsMobile.tsx
components/sections/IconTabs/IconTabsMobile/index.ts
components/sections/IconTabs/index.ts
components/sections/index.ts

Mobile:
Mobile portrait:
Tablet:

Add icon tabs mobile

---

components/sections/Footer/Footer.scss
components/sections/Footer/Footer.tsx

Desktop full:
Desktop min:
Tablet max:
Mobile:

[#39] Add style for desktop footer. Close #39

---

components/sections/home-banner/HomeBanner.scss

Fix button on top of mobile menu

---

components/Slider/Slider.scss
components/sections/IconTabs/IconTabsDesktop/IconTabsDesktop.scss
components/sections/Presentation/Presentation.tsx
components/sections/home-banner/HomeBanner.scss

[#60] Improve home banner text and hide slider scrollbar

---

__types__/ImpactBanner_data.graphql.ts
__types__/ImpactItem_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/sections/ImpactBanner/ImpactBanner.tsx
components/sections/ImpactBanner/components/ImpactItem/ImpactItem.tsx
package-lock.json
pages/[...site].tsx
schema/schema.graphql

Update types from Prismic

---

lib/createRelayEnvironment.js

Minify graphql query to avoid 414 status codes

---

__types__/GridSection_data.graphql.ts
__types__/SiteQuery.graphql.ts
components/sections/ColumnSection/ColumnSection.tsx
components/sections/Footer/Footer.scss
components/sections/Footer/Footer.tsx
components/sections/GridSection/GridSection.container.ts
components/sections/GridSection/GridSection.scss
components/sections/GridSection/GridSection.tsx
components/sections/GridSection/GridSection.types.ts
components/sections/GridSection/index.ts
components/sections/VerticalTabs/VerticalTabsDesktop/VerticalTabsDesktop.tsx
components/sections/VerticalTabs/VerticalTabsMobile/VerticalTabsMobile.tsx
components/sections/index.ts
pages/[...site].tsx
schema/schema.graphql
styles/global.scss

Brands section with new componenent Grid section

add grid section and brands container

---

components/sections/organizations/Organization/Organization.container.tsx
components/sections/organizations/Organization/Organization.scss
components/sections/organizations/Organization/Organization.tsx
components/sections/organizations/Organization/index.ts
components/sections/organizations/Organizations.scss
components/sections/organizations/TeamMember/TeamMember.scss
components/sections/organizations/TeamMember/index.ts

Add mobile version of the organization component.
It also changes a bit the desktop layout so it doesn't break with long names.

Add mobile version of organization

---

components/sections/Card/Card.scss
components/sections/GridSection/GridSection.scss
components/sections/Header/HeaderDesktop/HeaderDeskop.tsx
components/sections/Header/HeaderDesktop/HeaderDesktop.scss
components/sections/NewsBanner/NewsBanner.scss
components/sections/Tabs/TabsDesktop/TabsDesktop.scss
components/sections/TextCard/TextCard.scss
components/sections/VerticalTabs/VerticalTabsMobile/VerticalTabsMobile.scss
components/sections/home-banner/HomeBanner.scss
components/sections/organizations/Organizations.scss
styles/colors.scss
styles/global.scss

Add design review changes

---

components/sections/home-banner/HomeBanner.scss
components/sections/home-banner/HomeBanner.tsx

Add top gradient for header visibility

---

components/sections/Footer/Footer.scss

Center footer logo

---

components/sections/IconTabs/Content/Content.scss
components/sections/IconTabs/Content/Content.tsx
components/sections/IconTabs/IconTabsDesktop/IconTabsDesktop.scss

Before:
After:
Malnutrition content wasn't changed:

Fix content style

---

components/sections/NewsBanner/NewsBanner.scss

https://github.com/pata-pila/web/projects/1#card-49306532

[News Section] fix alignment

---

lib/fbPixelScript.ts
pages/[...site].tsx

This PR adds Facebook Pixel to the header of the page.

Add facebook pixel

---

lib/fbPixelScript.ts
pages/[...site].tsx

Revert "Add facebook pixel"

---

pages/[...site].tsx

This PR adds the google tag manager script.

Add google tag manager

---

pages/[...site].tsx

Change the tag and the Facebook script

Change tag script

---

pages/[...site].tsx

Add meta tag for domain verification facebook-domain-verification

Add metatag for facebook
